export const constAuth = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_LOGOUT: 'LOGIN_LOGOUT',
    TOKEN_TO_USER_REQUEST: 'TOKEN_TO_USER_REQUEST',
    TOKEN_TO_USER_SUCCESS: 'TOKEN_TO_USER_SUCCESS'
}