export const constTodo = {
    FETCHS_REQUEST: 'FETCH_TODOS_REQUEST',
    FETCHS_SUCCESS: 'FETCH_TODOS_SUCCESS',
    FETCHS_FAILURE: 'FETCH_TODOS_FAILURE',
    FETCHS_RESET: 'FETCH_TODOS_RESET',

    CREATE_REQUEST: 'CREATE_TODO_REQUEST',
    CREATE_SUCCESS: 'CREATE_TODO_SUCCESS',
    CREATE_FAILURE: 'CREATE_TODO_FAILURE',    

    FETCH_REQUEST: 'FETCH_TODO_REQUEST',
    FETCH_SUCCESS: 'FETCH_TODO_SUCCESS',
    FETCH_FAILURE: 'FETCH_TODO_FAILURE',

    DELETE_REQUEST: 'DELETE_TODO_REQUEST',
    DELETE_SUCCESS: 'DELETE_TODO_SUCCESS',
    DELETE_FAILURE: 'DELETE_TODO_FAILURE',        
}